""" Offline derivation of the QSSA G-coefficients.

This module is the offline tooling that produces the packaged coefficient
files under ``xqaa/data/`` (``qssa_fits_*.npz`` and ``qssa_bspline_*.npz``).
It is not used at retrieval time; it is run by hand to (re)generate those
files, and it requires ``ocpy`` for the reference Loisel+2023 data.
"""

import numpy as np

from scipy.optimize import curve_fit
from scipy.interpolate import make_interp_spline

from ocpy.hydrolight import loisel23

from xqaa import geometric
from xqaa import params as xqaa_params
from xqaa.qssa import io as qio


def rrs_func(uval: np.ndarray, G1: float, G2: float):
    """
    Evaluate the QSSA reflectance model ``rrs = G1*u + G2*u**2``.

    Parameters:
        uval (np.ndarray): The ratio u = bb/(a+bb).
        G1 (float): Linear-term coefficient.
        G2 (float): Quadratic-term coefficient.

    Returns:
        np.ndarray: Modelled sub-surface reflectance rrs.
    """
    rrs = G1 * uval + G2 * uval ** 2
    return rrs


def from_loisel23(params: xqaa_params.XQAAParams = None,
                  outfile: str = None, dw: int = 1):
    """
    Fit the QSSA coefficients to a Loisel+2023 variant and save them.

    Generated by JXP and Claude.

    Parameters:
        params (XQAAParams, optional): Selects the Loisel+2023 variant
            (``L23_X``/``L23_Y``) and, hence, the output filename. Defaults to
            ``XQAAParams()`` if not provided.
        outfile (str, optional): Explicit output path for the fit archive. If
            omitted, it is derived from ``params`` via
            :func:`xqaa.qssa.io.fits_filename`.
        dw (int): Stride for sub-sampling the wavelength grid.

    Returns:
        None. Writes an ``.npz`` archive (see :func:`fit_gordon`).
    """
    if params is None:
        params = xqaa_params.XQAAParams()
    if outfile is None:
        outfile = qio.fits_filename(params)

    # Load the selected Loisel+2023 variant
    l23_ds = loisel23.load_ds(params.L23_X, params.L23_Y)

    # Unpack the reflectance and IOPs
    l23_Rrs = l23_ds.Rrs.data
    l23_wave = l23_ds.Lambda.data
    a = l23_ds.a.data
    bb = l23_ds.bb.data

    # Fit per-wavelength and save
    fit_gordon(l23_wave[::dw], l23_Rrs[::dw], a[::dw], bb[::dw], outfile)
    return


def fit_gordon(wave: np.ndarray, Rrs: np.ndarray, a: np.ndarray,
               bb: np.ndarray, outfile: str):
    """
    Fit the QSSA quadratic per wavelength and save the coefficients.

    Generated by JXP and Claude.

    Parameters:
        wave (np.ndarray): Wavelengths [nm].
        Rrs (np.ndarray): Above-surface reflectance, shape (n_spectra, n_wave).
        a (np.ndarray): Total absorption, same shape as ``Rrs``.
        bb (np.ndarray): Total backscatter, same shape as ``Rrs``.
        outfile (str): Path for the output ``.npz`` archive.

    Returns:
        tuple: ``(waves, coeffs, covariances)`` as arrays; also written to
            ``outfile`` with keys ``ans``, ``cov``, ``wave``, ``rms``.
    """
    # u = bb / (a + bb)
    u = bb / (a + bb)

    # Sub-surface reflectance
    rrs = geometric.rrs_from_Rrs(Rrs)

    # Fit G1, G2 independently at each wavelength
    save_ans = []
    save_cov = []
    waves = []
    save_rms = []
    for ss, iwv in enumerate(wave):

        # Least-squares fit of the QSSA quadratic across all spectra
        ans, cov = curve_fit(rrs_func, u[:, ss], rrs[:, ss],
                             p0=[0.1, 0.1])
        # Fractional RMS of the fit
        irrs = rrs_func(u[:, ss], ans[0], ans[1])
        rms = np.sqrt(np.mean((rrs[:, ss] - irrs)**2/(irrs**2)))

        # Accumulate
        save_ans.append(ans)
        save_cov.append(cov)
        waves.append(iwv)
        save_rms.append(rms)

        # Progress
        print(f"wave={iwv}, ans={ans}, rms={100*rms}%")

    # Save the fit results
    np.savez(outfile, ans=save_ans, cov=save_cov, wave=waves, rms=save_rms)
    print(f'Saved to {outfile}')

    return np.array(waves), np.array(save_ans), np.array(save_cov)


def spline_me(params: xqaa_params.XQAAParams):
    """
    Fit B-splines to the saved QSSA coefficients and save them.

    Generated by JXP and Claude.

    Parameters:
        params (XQAAParams): Selects the fit archive to read
            (:func:`xqaa.qssa.io.fits_filename`) and the B-spline archive to
            write (:func:`xqaa.qssa.io.bspline_filename`).

    Returns:
        None. Writes an ``.npz`` archive with the two B-splines' knots,
            coefficients, and degrees.
    """
    # Load the previously-fit coefficients
    data_file = qio.fits_filename(params)
    d = np.load(data_file)

    # Unpack the per-wavelength G1, G2
    wave = d['wave']
    G1 = d['ans'][:, 0]
    G2 = d['ans'][:, 1]

    # Interpolating B-splines for each coefficient
    bspline_G1 = make_interp_spline(wave, G1)
    bspline_G2 = make_interp_spline(wave, G2)

    # Save the B-spline representations
    outfile = qio.bspline_filename(params)
    np.savez(outfile,
             t_H1=bspline_G1.t, c_H1=bspline_G1.c, k_H1=bspline_G1.k,
             t_H2=bspline_G2.t, c_H2=bspline_G2.c, k_H2=bspline_G2.k)
    print(f'Saved to {outfile}')


if __name__ == '__main__':

    # Regenerate the Loisel+2023 coefficient files for the shipped variants
    for X in [1, 4]:
        params = xqaa_params.XQAAParams(L23_X=X, L23_Y=0)
        # Fit the per-wavelength coefficients
        from_loisel23(params)
        # Spline them
        spline_me(params)
